# Site settings
title: Nickolas Selesky
email: developernick.ninja@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your portfolio here!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://developernick.github.io" # the base hostname & protocol for your site
twitter_username: nickds87
github_username:  nselesky

# Build settings
markdown: kramdown
